version: '3.8'

services:
  backend:
    build: .
    container_name: backend-ld
    ports:
      - "3300:3300"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=mssql
      - DB_PORT=1433
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
