name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPO: jmadurga/miapp-backend
      DEPLOYMENT: backend-deployment
      CONTAINER: backend
      NAMESPACE: default

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t $IMAGE_REPO:latest .

      - name: Push Docker image
        run: docker push $IMAGE_REPO:latest

      - name: Get image digest
        id: digest
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_REPO:latest)
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Fetch kubeconfig from DO
        run: |
          doctl kubernetes cluster kubeconfig save "${{ secrets.DO_K8S_CLUSTER_NAME_OR_ID }}" --expiry-seconds 600
          kubectl config current-context
          kubectl get nodes

      - name: Update deployment with digest
        run: |
          kubectl -n $NAMESPACE set image deployment/$DEPLOYMENT $CONTAINER=${{ steps.digest.outputs.digest }}
          kubectl -n $NAMESPACE rollout status deployment/$DEPLOYMENT --timeout=180s

